### ISSUE TITLE
How to query for declarations?

### ISSUE THREAD

**Issue by TedDriggs** [phenomnomnominal/tsquery#17]
I'm trying to figure out how to query for modules that are _not_ type declarations, so I tried starting with making a query for those that _are_. I've hit a brick wall, as I can't figure out how to say, "`ModuleDeclaration` whose `modifiers` contain a `DeclareKeyword` node".

```typescript
declare module foo {
  export const bar = (): {} => ({});
}
```

I tried `ModuleDeclaration[modifiers.0.kind]` which matched the above, but that stopped working when I tried either `ModuleDeclaration[modifiers.*.kind]` or `ModuleDeclaration[modifiers.0.kind = DeclareKeyword`, so I'm not sure how to avoid matching exported modules.

**Comment by TedDriggs** [comment]
Nvm, figured out that the `:has` selector does this.

**Comment by phenomnomnominal** [comment]
🎉
