### ISSUE TITLE
Can't query jsdoc tags

### ISSUE THREAD

**Issue by sandersn** [phenomnomnominal/tsquery#18]
I wanted to query for jsdoc tags as part of Microsoft/Typescript#24927, to help decide which syntax to support. Specifically, I wanted to know how people use `@this`:

```js
/** @this is the best day of my life
 * @return something
 */
function f() {
  return 1
}
```

Unfortunately, it looks like traverse relies exclusively on node.forEachChild, which skips jsdoc.

In the Typescript compiler, jsdoc is always accessed out-of-band, by explicitly requesting jsdoc from a node, so it's likely that traverse should add a call to getJSDocTags.

**Comment by phenomnomnominal** [comment]
Yeah, this is a good idea, I'd like to do a similar thing for being able to query the types. Just not sure quite how to implement, as I don't know what the perf hit would be like. It might be a case of just adding getters, so that if the query looks for the attribute it lazily does the call fo `getJSDocTags` or whatever type checker call.

**Comment by sandersn** [comment]
How do you tell if a query is interested in JSDoc? The query I tried was `Identifier[name="this']`, which *I think* should have worked (given my limited understanding of the query language).

I looked at the code again and I think basic support is as easy as saying `if (node.jsDoc) node.jsDoc.forEach(child => traverse(child, options))`. That would suffice for basic syntactic relationships; probably any users of tsquery could then figure out long-distance relationships (see example below) by calling `getJSDocTags` themselves on results of a query.

**Comment by sandersn** [comment]
OK, #19 provides a starting point for discussion. It *works*, but it's hacky.
