### ISSUE TITLE
Feature proposal: tsquery.map

### ISSUE THREAD

**Issue by urish** [phenomnomnominal/tsquery#21]
A function that takes a query and a callback, and invokes the callback for each match, and if the callback returns a new node, replaces the original node with the new node.

Example:

```ts
import * as ts from 'typescript';
import { tsquery } from '@phenomnomnominal/tsquery';

function addPrefix(node: ts.Identifier) {
  return ts.createIdentifier('foo_' + node.text);
}

const sourceFile = tsquery.ast('function hello() { return "world" }');
const newSource = tsquery.map(sourceFile, 'FunctionDeclaration>Identifier', addPrefix);
const result = ts.createPrinter().printFile(newSource);
console.log(result);
```

and the result would be: `function foo_hello() { return "world" }`;

This will be very useful for writing TS transforms (e.g. for schematics). Thoughts?

**Comment by phenomnomnominal** [comment]
Yeah, that's dope, and should be pretty straightforward too.

**Comment by urish** [comment]
Another idea would be to support modifying the given source code directly by replacing the matches with a given string.  Could be implemented either as a feature of `tsquery.map()`, or as a separate `tsquery.replace()` function, as in the example below:

```ts
tsquery.replace(
  'function hello() { return "world" }',
  'FunctionDeclaration>Identifier',
  'foo'
);

// Returns: function foo() { return "world" }
```

or as a callback:
```ts
tsquery.replace(
  'function hello() { return "world" }',
  'FunctionDeclaration>Identifier',
  node => 'foo_' + node.text
);

// Returns: function foo_hello() { return "world" }
```

Ideally, the 2nd form will also support `null` or `undefined` return value, which would mean to skip replacing the current node.

**Comment by phenomnomnominal** [comment]
Had a hoon on some of this here: https://github.com/phenomnomnominal/tsquery/tree/get-ready-for-2.0.0
