### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by bajtos** [phenomnomnominal/tsquery#25]
Could you please add a LICENSE file to your repository to clearly spell out the license terms?

The file `package.json` says the license is MIT. I believe that is not sufficient, although IANAL and may be wrong.

https://github.com/phenomnomnominal/tsquery/blob/4fe8a183fb044c0386f46621805c17e73a51fba7/package.json#L12

You can find a template for MIT license here: https://opensource.org/licenses/MIT

**Comment by phenomnomnominal** [comment]
Done 😄 , sorry about this!

**Comment by bajtos** [comment]
Lovely ❤️ Thank you for such a quick response 🙇
