### ISSUE TITLE
General Question on the typescript dependency

### ISSUE THREAD

**Issue by marioestradarosa** [phenomnomnominal/tsquery#26]
Thanks for the **great tsquery library** !

- Is there any reason why the package doesn't include the typescript as a dependency as opposed to the current devDependency only?.  

- Client applications using your library have to install typescript separately in the current behavior, is this correct?

**Comment by phenomnomnominal** [comment]
Hey there! Yes you’re right, `typescript ` should absolutely be a `peerDependency` instead of a `devDependency`! It’s kind of funny no-one’s noticed this yet. I’ll try to get it sorted today.

**Comment by marioestradarosa** [comment]
Lovely, thank you very much. This library looks great so far. I will check tomorrow if the npm package has been updated. Thanks for the prompt response.

**Comment by phenomnomnominal** [comment]
Published with the `peerDependency` in `@phenomnomnominal/tsquery@2.0.1`
