### ISSUE TITLE
Support vscode and webstorm 

### ISSUE THREAD

**Issue by ArielGueta** [phenomnomnominal/tsquery#28]
Thanks for this great library. 

I create a custom rule successfully, but unfortunately, when using the vscode tslint plugin, I can't see the error ( the red curly brackets ).

Here is my code:

```ts
export class Rule extends Lint.Rules.AbstractRule {
  public static FAILURE_STRING = (path: string) => {
    return `${path} - debugger statement forbidden;`;
  }

  public apply(sourceFile: ts.SourceFile): Lint.RuleFailure[] {
    const nodes = tsquery(sourceFile, 'DebuggerStatement');
    return nodes.map(result => {
      return new RuleFailure(
        result.getSourceFile(),
        result.getStart(),
        result.getEnd(),
        Rule.FAILURE_STRING(sourceFile.fileName),
        this.ruleName
      );
    });
  }
}
```

Do you have any idea why?

Thanks.

**Comment by phenomnomnominal** [comment]
How interesting! I really don't know... does the [tslint no-debugger](https://palantir.github.io/tslint/rules/no-debugger/) rule work? I wonder if they're somehow cancelling each other out?

**Comment by ArielGueta** [comment]
Yes, it's working. When running ng lint I'm getting `[12, 5]: debugger statement forbidden`

**Comment by ArielGueta** [comment]
replaced no-debugger with no-my-debugger

**Comment by phenomnomnominal** [comment]
Any obvious differences with the other custom rule?

**Comment by ArielGueta** [comment]
They don't use tsquery :)

**Comment by ArielGueta** [comment]
https://github.com/mgechev/codelyzer/blob/master/src/noLifeCycleCallRule.ts

This is the custom rule that works.

**Comment by ArielGueta** [comment]
Maybe the following line? 
`this.addFailureAtNode(node, Rule.FAILURE_STRING);`

**Comment by ArielGueta** [comment]
I also see a [metadata](https://github.com/mgechev/codelyzer/blob/master/src/noLifeCycleCallRule.ts#L6) that displayed in vscode when hovering the error.
![image](https://user-images.githubusercontent.com/20522870/46459558-ee929700-c7c1-11e8-8cb5-4cba624dbce8.png)

**Comment by phenomnomnominal** [comment]
Quite possibly, just looking at this:

https://github.com/palantir/tslint/blob/c01bb2cdc258da4f9727781151d91773fba3e283/src/language/walker/walkContext.ts

Is the plugin OS?

**Comment by ArielGueta** [comment]
Sorry, what do you mean by saying OS?

**Comment by phenomnomnominal** [comment]
Open source :)

**Comment by ArielGueta** [comment]
Yes. https://github.com/Microsoft/vscode-tslint/

**Comment by phenomnomnominal** [comment]
just trying to figure out how to debug this! I'll hopefully figure it out soon

**Comment by ArielGueta** [comment]
Thanks!

**Comment by phenomnomnominal** [comment]
Have you compiled your rules? Is it possibly related to this: https://github.com/Microsoft/vscode-tslint/issues/313 ?

**Comment by ArielGueta** [comment]
Hey man, sorry for the hassle, this link solved it: https://github.com/Microsoft/vscode-tslint/issues/344#issuecomment-388531147

**Comment by ArielGueta** [comment]
I just restart my vscode and it worked like a charm! Thanks and sorry.

**Comment by ArielGueta** [comment]
![image](https://user-images.githubusercontent.com/20522870/46472508-13990100-c7e6-11e8-8ddd-91f01f479dba.png)

**Comment by phenomnomnominal** [comment]
Oh great! Good to hear!
