### ISSUE TITLE
Querying a super class with tsquery

### ISSUE THREAD

**Issue by ArielGueta** [phenomnomnominal/tsquery#30]
I'm wondering if there is a way to query a `super()` class. For example, let's say I have a child that extends other class and I want to check if a method exists on the **parent** class.

Thanks.

**Comment by phenomnomnominal** [comment]
Yep, totally possible, but would require a bit of work.

Something like:

```typescript
tsquery(ast, 'ClassDeclaration > HeritageClause Identifier').forEach(superClassName => {
    const importPath = tsquery(ast, `ImportDeclaration:has(Identifier[name="${superClassName}"]) StringLiteral`);
    const superClassPath = path.resolve(ast.filePath, importPath.value);
    const superClassFile = fs.readFileSync(superClassPath, 'utf8');
    const superClassAst = tsquery.ast(superClassFile);
    const methods = tsquery(superClassAst, 'MethodDeclaration');
});
```

Note, this is definitely untested and definitely pseudocode 😄, but it might get you started.
