### ISSUE TITLE
Clarity on selecting a node that has specific nodes

### ISSUE THREAD

**Issue by Cammisuli** [phenomnomnominal/tsquery#31]
Hi there, I'm trying to select a specific `CallExpression` that has an specific `Identifier`. So I came to the following query: `ExpressionStatement > CallExpression:has(Identifier[name="beforeEach")`

Using that query, I get a bunch of nodes that have a `CallExpression` that **does not** have the Identifier I specified. But returned nodes that had the `beforeEach` identifier within it's children. 

I have this stackblitz to better show what I mean:
https://stackblitz.com/edit/tsquery-example-1-hjj1o1?file=index.ts

So the question I have, does including `:has` keep going down the children? Am I using the `has` or even constructing this query properly?

**Comment by phenomnomnominal** [comment]
Hey! Yeah, `:has` will look into all the children (and children's children etc) from a particular node. It's not great 😅, I've been looking into the underlying esquery parser to enable something like `CallExpression:has(> Identifier)`.

For now, your best bet is to simply do this:

```ts
CallExpression[expression.name="beforeEach"]
```

That will interrogate the specific properties of the Call Expression that you're after. I find https://astexplorer.net/ useful in figuring this kind of thing out.

Hope that helps!

**Comment by Cammisuli** [comment]
Thanks for the assistance and clarification! That was actually simpler than I expected :D
