### ISSUE TITLE
Adding properties to nodes causes problems in typescript-tslint-plugin

### ISSUE THREAD

**Issue by cartant** [phenomnomnominal/tsquery#32]
I've had an issue opened for `rxjs-tslint-rules`: https://github.com/cartant/rxjs-tslint-rules/issues/59

There seems to be a problem caused by `tsquery` in [Microsoft/typescript-tslint-plugin](https://github.com/Microsoft/typescript-tslint-plugin). And the problem seems to be [due to the adding of properties to the TypeScript nodes](https://github.com/Microsoft/typescript-tslint-plugin/issues/8#issuecomment-433233845) - [here](https://github.com/phenomnomnominal/tsquery/blob/b860737c82471a130042fb1df80c0abe12799b45/src/traverse.ts#L63).

Do the properties have to be added for reasons associated with the use of `esquery`? Or could a `WeakMap` be used instead of adding properties to the nodes?

**Comment by phenomnomnominal** [comment]
Hmm I can’t look at the code right now, but I’m pretty sure it was just about getting API equivalence. I reckon most/all of the functionality could be done with a `WeakMap`. I’ll have a crack.

**Comment by cartant** [comment]
FYI, I've had a quick stab at replacing the node mutation with a `WeakMap`. The tests pass. I'll verify that this actually solves the reported problem before considering submitting a PR.

**Comment by phenomnomnominal** [comment]
Just merged @cartant's PR, so if someone could try @phenomnomnominal/tsquery@3.0.0 and see if it works?

**Comment by cartant** [comment]
Yep, it fixes the problem: https://github.com/cartant/rxjs-tslint-rules/issues/59#issuecomment-436755881
