### ISSUE TITLE
Supported Node Kinds?

### ISSUE THREAD

**Issue by manfredsteyer** [phenomnomnominal/tsquery#4]
Hi,

I've noticed that while ``tsquery(ast, 'ClassDeclaration');`` brings a a value, ``tsquery(ast, 'ClassKeyword');`` dosn't. What's the reason for this? How can I find out which node kinds I can use in queries?

**Comment by phenomnomnominal** [comment]
What kind of `value` does it return? It's only meant to do that for things that are `Literal`s, so I may have a bug :)

**Comment by manfredsteyer** [comment]
With "no value" I meant an empty array:

```
const ctorNodes = tsquery(ast, 'ClassKeyword');
console.log(ctorNodes.length === 0);  // TRUE
```

I've seen the same for nodes of the kind ``SyntaxList``. And perhaps other node kinds are affected as well.

Did I understand something wrong or is this a bug?

**Comment by manfredsteyer** [comment]
I can see those branches when I visualize the AST using sth like the following function.

Can I query those nodes in an other way?

I'd need some way to express: Give me the ``constructor`` node which is a child of the node with a ``class`` keyword followed by the name ``MyClass`` etc.

```
function showTree(node: ts.Node, indent: string = '    '): void {

    console.log(indent + ts.SyntaxKind[node.kind]);
    if (node.getChildCount() === 0) {
        console.log(indent + '    Text: ' + node.getText());
    }

    for (const child of node.getChildren()) {
        showTree(child, indent + '    ');
    }
}
```

**Comment by phenomnomnominal** [comment]
Yeah, so that's exactly what `tsquery` is designed for!

Given something like this:

```
const ast = tsquery.ast(`
    export class MyClass {
        constructor () { }
    }
`);
```

You could express it like this:

```
tsquery(foo, 'ClassDeclaration[name.name="MyClass"] > Constructor');
```

**Comment by manfredsteyer** [comment]
Thanks for this. This works.

But I'm still not sure why tsquery ignores some nodes, the ``showTree`` helper function above displays. Can you pls give me some hints towards that?

**Comment by urish** [comment]
@manfredsteyer in your function you use `getChildren()` to traverse the tree. TSQuery uses [forEachChild](https://github.com/phenomnomnominal/tsquery/blob/7eb882084fb65555dd58d7c72f394bea6eb72b88/src/traverse.ts#L29). You can modify your `showTree()` helper function as follows to get the same tree as TSQuery sees:

```ts
function showTree(node, indent: string = '    '): void {
    console.log(indent + ts.SyntaxKind[node.kind]);
    if (node.getChildCount() === 0) {
        console.log(indent + '    Text: ' + node.getText());
    }

    node.forEachChild(child => {
        showTree(child, indent + '    ');
    });
}
```

**Comment by manfredsteyer** [comment]
Ah, cool, now everything makes sense for me. Thx, @urish !
