### ISSUE TITLE
Can't scroll on the playground

### ISSUE THREAD

**Issue by maxime1992** [phenomnomnominal/tsquery#43]
It appears that it's impossible to scroll when there's a large piece of code.

Neither on the code nor the query result.

**Comment by phenomnomnominal** [comment]
Hey! That's not very good! Would you mind raising a issue on the playground repo: https://github.com/urish/tsquery-playground

**Comment by maxime1992** [comment]
I searched for that repo under your username didn't realize that it's been done on Urish's repo :smile: 

Closing in favor of https://github.com/urish/tsquery-playground/issues/4

Thanks!
