### ISSUE TITLE
Enhancement: add tsquery.replace example into main readme

### ISSUE THREAD

**Issue by yrtimiD** [phenomnomnominal/tsquery#50]
It was hard to discover its existence and usage

**Comment by SerkanSipahi** [comment]
@yrtimiD can you create a PR for that, thanks 💯

**Comment by kroeder** [comment]
There's a test file that shows an example

https://github.com/phenomnomnominal/tsquery/blob/master/test/replace.spec.ts

**Comment by phenomnomnominal** [comment]
Done finally lol, also made `replace` work better.
