### ISSUE TITLE
Select parameter of a given method

### ISSUE THREAD

**Issue by kalpeshhpatel** [phenomnomnominal/tsquery#52]
For the following class declaration:

```
class ABC {

	method1(c: string) {
    
         }
  
  	method2(d: number) {
    
        }
  
}
```

How can I select parameters of the `method1` using tsquery.

I tried the following:

`ClassDeclaration > MethodDeclaration Identifier[name=method1"] Parameter`

But didn't work out.

Also,

`ClassDeclaration > MethodDeclaration Parameter`

selects all the parameter nodes.

Any suggestions please?

Thanks

**Comment by phenomnomnominal** [comment]
Couple issues here, firstly you have a stray `"`. You want either `[name="method1"]` or `[name=method1]`. Secondly, the tree doesn't quite work how your query suggests - the `Paramater` isn't a child of the `Identifier`. You want to find a `MethodDeclaration` that has the name `method1`, and then get the `Parameter`. So your full query should be something like:

`ClassDeclaration > MethodDeclaration:has(Identifier[name="method1"]) Parameter`
