### ISSUE TITLE
Cannot set property text of #<IdentifierObject> which has only a getter

### ISSUE THREAD

**Issue by urish** [phenomnomnominal/tsquery#6]
Input that causes this error:

```typescript
function test() {
  "bar",
}
```

While this code is not syntactically valid, TypeScript can still generate an AST for it, and I believe it would be best if we can make sure TSQuery wouldn't throw an error for this input.

**Comment by urish** [comment]
Found another input that causes this error, here is the code to reproduce:

```typescript
const ast = tsquery.ast('function(){}');
tsquery(ast, 'FunctionDeclaration');
// you get: ​​Cannot set property text of #<IdentifierObject> which has only a getter
```

If you give the function a name (i.e. `function f(){}`), then the error goes away.

**Comment by phenomnomnominal** [comment]
Nice, I thought I checked for the presence of that property before setting it, but I must have missed one. I’ll sort it out now.

**Comment by urish** [comment]
Thank you my friend :)

p.s. I'm working right now on a new project on top of TSQuery - stay tuned for a nice surprise :)
