### ISSUE TITLE
type parameters are missing

### ISSUE THREAD

**Issue by ahfarmer** [phenomnomnominal/tsquery#65]
Hi there - great and very interesting project. But are type parameters selectable?

Using `TypeParameter` as the selector returns an empty array:

```
const tsquery = require("@phenomnomnominal/tsquery").tsquery;

const ast = tsquery.ast(`
const saveStateLabelFamily = selectorFamily<string, EntityId>({
  key: "SaveStateLabelFamily",
});
`);

console.log(tsquery(ast, "TypeParameter"));
```

Pasting my code into the playground at https://tsquery-playground.firebaseapp.com/ reveals that there are no type-specific nodes in the tree. The types look like children of the call expression.

<img width="1430" alt="Screen Shot 2021-06-30 at 2 22 17 PM" src="https://user-images.githubusercontent.com/597825/124033501-dd950580-d9ae-11eb-96f0-f0426a8f7357.png">

**Comment by phenomnomnominal** [comment]
`TypeParameter` is a valid SyntaxKind, but I guess they're not queryable as a group from the AST. `StringKeyword` and `TypeReference` are the type parameters in this instance.

You can access them like this:

```
const [call] = tsquery(`
    const saveStateLabelFamily = selectorFamily<string, EntityId>({
      key: "SaveStateLabelFamily",
    });
`, 'CallExpression');
const typeParameters = call.typeArguments;
```

**Comment by ahfarmer** [comment]
Ah, interesting. Thanks for the reply! 

Where is it decided what is queryable? Is that in `tsquery` or in babel? I'm looking for a solution where a single selector is sufficient to access any node in the AST.

**Comment by phenomnomnominal** [comment]
`tsquery` only uses the AST produced by TypeScript, not by Babel, so it all depends on the traversal algorithm provided by TypeScript. It is pretty unlikely that you'll get one query for all situations, but you might be able to combine selectors, something like `CallExpression, FunctionDeclaration, NewExpression`... and find all the types of nodes that can have `typeArguments`?

**Comment by ahfarmer** [comment]
Ah, no I didn't mean I'm trying to access all the types at once with a single selector. I meant that a single selector should be sufficient to access any specific part of the document in a fine-grained way.

I'm interested in writing a tool with a single input box in which the user can type in a query. I want that query to be able to access any part of the document including the type information. I can't grab the object and call `typeArguments` on it.

**Comment by phenomnomnominal** [comment]
Ah, I just tried again, and it seems to be the difference between using `TypeParameter` and `TypeReference`:

```
function foo <string, T>(a: T) {
}

const saveStateLabelFamily = selectorFamily<string, EntityId>({
  key: "SaveStateLabelFamily",
});
```

`(a: T)` and `selectorFamily<string, EntityId>` <- `T` and `EntitiyId` are `TypeReferences`
`<string, T>` <- `string` and `T` are `TypeParameter`

**Comment by ahfarmer** [comment]
Hmmm - yeah I think using `TypeReference` in my example was a mistake. Here's a simple example to work with: 

```typescript
const label = foo<string>(null)
```

Is it possible to write a selector that selects the type parameter on the `foo()` function? (to get the string?)

I've tried both of these selectors without success:
```
CallExpression TypeParameter
CallExpression TypeReference
```

I can select the part I want with  `CallExpression StringKeyword` but thats not useful to me because I'm dealing with code that has different types involved, like this:

```typescript
const sushi = foo<string>("")
const potato = bar<number>(1)
```

**Comment by phenomnomnominal** [comment]
Oh, you could totally just use a field selector: `CallExpression .typeArguments`. I think that should do the trick.

**Comment by ahfarmer** [comment]
`CallExpression .typeArguments` is exactly what I was looking for. Thank you 🙏
