### ISSUE TITLE
Add support for comments and multiple lines

### ISSUE THREAD

**Issue by iddan** [phenomnomnominal/tsquery#69]
This tool is amazing, I'm not sure if this should be opened here or in esquery but I think a great addition would be to support comments and multiple lines as it makes writing complex queries a lot easier.
For example: a query I wrote with comments and new lines (I'm stripping them before passing them to tsquery):
```css
/* title attribute */
JsxAttribute[name.name=/title|label|alt/] StringLiteral,

/* JsxText which content is not only whitespace */
JsxText:not([text=/^\s+$/])
```
And this how it looks without comments and new lines:
```css
JsxAttribute[name.name=/title|label|alt/] StringLiteral, JsxText:not([text=/^\s+$/])
```

**Comment by iddan** [comment]
Thank you so much! Much appreciated

**Comment by phenomnomnominal** [comment]
You're welcome!
