### ISSUE TITLE
Node 16 support

### ISSUE THREAD

**Issue by MaxKless** [phenomnomnominal/tsquery#74]
Hi, currently using tsquery with the new Node 16 throws all kinds of errors. Do you plan on supporting it?

**Comment by phenomnomnominal** [comment]
What errors are you seeing specifically? My tests pass on Node 16 (and 17)

**Comment by MaxKless** [comment]
Hi, so sorry for opening this issue and then not responding. 
I think the issues looked like they were missing tsquery support but it wasn't actually the case.

My bad, thanks for the work you do :)
