### ISSUE TITLE
Cannot query Identifier under ExportKeyword

### ISSUE THREAD

**Issue by winston0410** [phenomnomnominal/tsquery#82]
I am not sure if I am writing the query incorrectly or this is a bug. I tried to query the `get` in this code:

```typescript
export const get = () => {}
```
With the following query, but it returns an empty array to me. Is my query incorrect?

```typescript
import { tsquery } from '@phenomnomnominal/tsquery'

const code = `export const get = () => {}`
const ast = tsquery.ast(code)
const node = tsquery(ast, 'ExportKeyword Identifier[name=get]');
console.log(node)
```

**Comment by phenomnomnominal** [comment]
So in this case what you might want is `VariableStatement:has(ExportKeyword) Identifier[name=get]`. `ExportKeyword` and `Identifier` are both siblings, and they're children of the `VariableStatement`

You can use https://tsquery-playground.firebaseapp.com/ to help with these things.
