### ISSUE TITLE
Case insensitive regex

### ISSUE THREAD

**Issue by arturohernandez10** [phenomnomnominal/tsquery#91]
This is odd I get the following error when doing a search like ```Identifier[name=/CAPTCHA/i]```

```
SyntaxError: Expected " " or "]" but "i" found.
```

And I looked at esquery 1.4.0. The peg script is:

```
    flags = [imsu]+
    regex = "/" d:[^/]+ "/" flgs:flags? { return {
      type: 'regexp', value: new RegExp(d.join(''), flgs ? flgs.join('') : '') };
    }
```

Which suggests it should work just fine. I may need to test directly on esquery.

**Comment by phenomnomnominal** [comment]
Added a test for this in v6, it seems to work. Maybe fixed when I upgraded the `esquery` dependency?
