### ISSUE TITLE
Sibling selectors no longer work

### ISSUE THREAD

**Issue by njx** [phenomnomnominal/tsquery#92]
The `~` and `+` selectors don't seem to work in the latest version of tsquery:

```
import { tsquery } from "@phenomnomnominal/tsquery";

const ast = tsquery.ast("class Foo { bar = 'baz'; }");
const identifier = tsquery(ast, "PropertyDeclaration > Identifier[name='bar']");
console.log("identifiers found:", identifier.length);
const value = tsquery(ast, "PropertyDeclaration > Identifier[name='bar'] ~ StringLiteral");
console.log("values found:", value.length);
```

finds 1 identifier but 0 values. This seems to work in the [TSQuery Playground](https://tsquery-playground.firebaseapp.com/), which looks like it's based on an older version of tsquery.

**Comment by phenomnomnominal** [comment]
This isn't a very satisfying solution, but as you can see from [this test](https://github.com/phenomnomnominal/tsquery/blob/master/test/sibling.spec.ts#L20), you need to use the `visitAllChildren` flag. Hopefully that helps!

It's probably about time I make that the default and push a breaking change tbh.

**Comment by phenomnomnominal** [comment]
^ This is now the default behaviour in v6
