### ISSUE TITLE
Possible issues with the child selectors with version 6.1

### ISSUE THREAD

**Issue by nzacca** [phenomnomnominal/tsquery#95]
Hello!

There appears to be some bugs with `*-child` selectors in v6. Consider the following scenarios:

```ts
const contents = `import { foo } from "@foo";`;

// Pass v5 and v6
tsquery.query(contents, `ImportDeclaration`);                   

// Fail v5, expected
// Pass v6, unexpected
tsquery.query(contents, `ImportDeclaration:nth-child(0)`);      

// Pass v5
// Fail v6, unexpected
tsquery.query(contents, `ImportDeclaration:nth-child(1)`);      

// Pass v5
// Fail v6, unexpected
tsquery.query(contents, `ImportDeclaration:first-child`);       

// Pass v5
// Fail v6, unexpected
tsquery.query(contents, `ImportDeclaration:last-child`);

// Pass v5
// Fail v6, unexpected
tsquery.query(contents, `ImportDeclaration:nth-last-child(1)`);

// Fail v5, expected
// Pass v6, unexpected
tsquery.query(contents, `ImportDeclaration:nth-last-child(3)`);
```

Note that the behavior in v5.0.1 works as expected.

**Comment by phenomnomnominal** [comment]
Good catch, turns out I deleted some code I shouldn't have 🤣. Fixed in 6.1.2 and added tests so it doesn't happen again!

**Comment by nzacca** [comment]
@phenomnomnominal 

Thank you for the quick turn around. I had a look and I _think_ there's an extra `debugger` statement left in the code: https://github.com/phenomnomnominal/tsquery/commit/d80bcde1eff10bee62c7b5d3e7dce1960ccad007#r121384153

**Comment by phenomnomnominal** [comment]
Yeah it’s in the code but not the published package, I must not have pushed my final commit. Will fix when at my computer!

**Comment by nzacca** [comment]
Thanks @phenomnomnominal . I can confirm that 6.1.2 works as expected. Thanks again!
